- alpine/Dockerfile
Hi there
The Dockerfile has been completed, but the official docker image 500 happened when `require "ngx.re"`, I should wait openresty/docker-openresty/pull/113 merge. 
--- 2019-07-12 updated
The official docker image was fixed pcre bug in [1.15.8.1-3](https://github.com/openresty/docker-openresty/blob/master/CHANGELOG.md#11581-3) , and I was modified the Dockerfile.
> Add Dockerfile for alpine

- example/apisix_conf/config.yaml
nginx: [warn] low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:82
nginx: [warn] low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:112
fixed 127.0.0.1/24 to 127.0.0.0/24
see: https://github.com/iresty/apisix#dashboard
> fixed: allow_admin address error in config.yaml

- all-in-one/apisix-dashboard/Dockerfile
Signed-off-by: imjoey <majunjiev@gmail.com>
Related to issue https://github.com/apache/apisix-dashboard/issues/1145 .
This PR is going to set the variable `APISIX_DASHBOARD_VERSION` to `master`, and then we can use the latest code from master branch, instead of a specified release version. This is similar to PR https://github.com/apache/apisix-dashboard/pull/1146 which would fix the one within `apache/apisix-dashboard` repo. Thanks.
> fix: use the code from master branch to build dashboard image

- README.md
- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine/Dockerfile
Previously, the `aliyun` mirror is always used in docker build phrase and it's honestly not properly set for non-Chinese users.
Changes proposed in this PR:
- Introduce a new build argument `ENABLE_PROXY` in Dockerfile for APISIX, building will use proxy if `ENABLE_PROXY` is set to `true`
- Add guides for the new `ENABLE_PROXY`
- Reduce the count of individual `RUN` commands in Dockerfile for Dashboard to reduce the image size as well as the build time cost
- Make Dockerfile be more conventional via some other minor changes
> feat: Support ENABLE_PROXY argument at building phrase for mirror switch

- .github/workflows/linux_alpine_ci.yaml
- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine/Dockerfile
Fix: `/usr/bin/apisix` use `bash` after version 2.3.
> fix: modify dockerfile  when apisix version > 2.2

- .github/workflows/apisix_all_in_one_ci.yaml
- .github/workflows/dashboard_all_in_one_ci.yaml
- all-in-one/apisix-dashboard/Dockerfile
`apisix_all_in_one_ci.yaml` and `dashboard_all_in_one_ci.yaml`should be executed in the phase of pull_request.
Related to #126
> ci: execute ci about apisix and dashboard when pull_request

- README.md
- alpine/Dockerfile
- centos/Dockerfile
- example/docker-compose.yml
Signed-off-by: imjoey <majunjie@apache.org>
As the releases of APISIX 2.3 and dashboard 2.4, this PR is going to upgrade the default versions in relevant dockerfiles and docs. This would let users have the latest stable releases by default.
> feat: Upgrade default versions of apisix and apisix-dashboard

- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
The default [`alpine-fat`](https://hub.docker.com/layers/openresty/openresty/alpine-fat/images/sha256-87b7cddf36e76c42da26143e049745f58e341efa21e6471fc71cab188c42bc48?context=explore) uses openresty `v1.15.8.3`, which APISIX have already discarded. So we need to explicitly specify openresty version
Ref: https://github.com/apache/apisix/pull/3912/checks?check_run_id=2198667421#step:7:354
> fix: use openresy 1.19.3.1 as alpine's base image

- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
- centos/Dockerfile
usage:
```
environment:
- "TZ=Asia/Shanghai"
```
> feat: timezone support via startup environment `TZ`

- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
musl	CVE-2020-28928	 	fixed in 1.2.2_pre2-r0	4	
Published: >4 months agoIn musl libc through 1.2.1, wcsnrtombs mishandles particular combinations of destination buffer size and source character limit, as demonstrated by an invalid write access (buffer overflow).
xref: https://nvd.nist.gov/vuln/detail/CVE-2020-28928
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
> fix: upgrade alpine version due to CVE-2020-28928

- example/docker-compose-alpine.yml
- example/docker-compose.yml
In this example, it is not necessary to specify static ip to complete its function.
If static ip is specified, the operation will fail due to network segment conflicts.
> fix: remove example/docker-compose.yml static ip address

- docs/en/latest/manual.md
fix: [#325](https://github.com/apache/apisix-website/issues/325)
> docs: broken link in docker manual page

- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
Reverts apache/apisix-docker#162, since it seems luarocks get back to work
Related to https://github.com/apache/apisix/pull/4038
> ci: revert "fix: build failure caused by luarocks connection"

- .github/workflows/apisix_push_docker_hub.yaml
- .github/workflows/dashboard_push_docker_hub.yaml
- MAINTAINING.md
- Makefile
1. change new release trigger from release to release branch, to simplify new release publishment process
2. also push latest image when make release
> ci: change new release trigger from release to release branch

- .github/workflows/apisix_push_docker_hub.yaml
- .github/workflows/dashboard_push_docker_hub.yaml
- Makefile
So it would be easier to run on Mac M1 😿 
Ref: 
1. https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
2. https://github.com/docker/buildx
> ci: release on multiarch for apisix image on alpine

- alpine-local/Dockerfile
The `authz-casbin` plugin requires PCRE package installed and hence it failed the chaos test. This PR adds the package as dependency.
([Context](https://github.com/apache/apisix/pull/4710#discussion_r680569232))
> ci: Add PCRE package for dependency installation

- README.md
- all-in-one/apisix-dashboard/conf.yaml
- all-in-one/apisix/config.yaml
- compose/docker-compose.yaml
- docs/en/latest/manual.md
- example/apisix_conf/config.yaml
- example/docker-compose-alpine.yml
- example/docker-compose.yml
> chore: use the correct prometheus port for docker compose

- example/docker-compose-arm64.yml
Signed-off-by: imjoey <majunjie@apache.org>
This PR is going to add the docker-compose configurations for ARM64. Since apisix-dashboard has no arm64 image yet, so only apisix is included. 
The OS for testing is shown as below:
Here is the test result:
Actually, we do need a CI for continuous testing. Still looking for proper CI resources with ARM64.
> feat: Add docker-compose config for arm64

- example/docker-compose-alpine.yml
- example/docker-compose.yml
#174 Etcd Startup still has permissions issues.
```
os: buster
docker: 20.10.8
```
Signed-off-by: ysicing <i@ysicing.me>
> fix(etcd): fix etcd startup report permission issue

- docs/en/latest/build.md
1. update APISIX version to `2.9`
2. use make instead of docker cmd in docs, more elegant
Signed-off-by: leslie tsang <leslie.tsang@icloud.com>
> docs: use make instead of docker

- Makefile
1. add more makefile target output prompts
2. fix target `help` prompts to sync with linux runtime
> before
```bash
docker build output ...
```
> after
```bash
[ info ] build-on-centos -> [ Start  ]
docker build output ...
[ info ] build-on-centos -> [ Done  ]
```
> chore: add more makefile output prompts

- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
> chore: update apisix base docker images version

- .github/workflows/apisix-docker-test.yaml
- Makefile
- alpine/Dockerfile
- centos/Dockerfile
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
> feat: upgrade APISIX to 2.10.2

- .github/workflows/dashboard-docker-test.yaml
- .github/workflows/dashboard_push_docker_hub.yaml
- Makefile
- README.md
- dashboard/Dockerfile
- example/docker-compose.yml
Upgrade the latest version of APISIX Dashbaord 2.10 while supporting multi-architecture build and push.
> feat: bump APISIX Dashboard to 2.10

- alpine-local/Dockerfile
The apisix-base version is not up-to-date. So we fall back to use
OpenResty to let CI pass.
See https://github.com/apache/apisix/pull/5943.
TODO: use CI to provide a latest apisix-base image.
> fix: rollback the docker image used in chaos test

- alpine-dev/Dockerfile
Please don‘t merge until `api7/apisix-base:1.19.9.1.2` has been pushed.
> feat: update apisix-base version to 1.19.9.1.2

- example/docker-compose.yml
from 2.11.0-alpine to 2.12.0-alpine
> chore: update apisix image version in example

- .github/workflows/apisix_dev_push_docker_hub.yaml
- Makefile
- README.md
This CI will build the APISIX master branch code into the docker hub repository at 0:00 UTC every day, so that developers can experience and test the new features in a timely manner.
> ci(apisix-dev): timed sync apisix-dev image

- .github/workflows/dashboard_push_docker_hub.yaml
- Makefile
I found the typo error(maybe).
Reproduction:
run make help;
and find the command make push-multiarch-dashbaord (please notice the dashbaord)
Change all **dashbaord** to **dashboard**.
#301
> chore: typo error, change dashbaord to dashboard

- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
This fix is from https://github.com/apache/apisix-docker/pull/287.
Look like it is missing in the dev image
Reported in https://the-asf.slack.com/archives/CUC5MN17A/p1652951422223499?thread_ts=1652868150.081189&cid=CUC5MN17A
> fix: apply PCRE path fix to alpine-dev & all-in-one

- README.md
Update README.md:
- add a **Summary** section, which briefly what this repo contains
- add doc for images in the beginning in **How to Build Images**
- add **Run With Docker-compose**
- add **Useful Commands**
Need info for: 
- supported platforms for each command
Any suggestion or fix is appreciated :)
> Add doc for docker-compose, makefile commands, and images in README.md

- example/docker-compose-arm64.yml
The docker compose file misses the environment parameter for the etc data directory.
> Add missing env parameter for etc data dir

- centos/Dockerfile
Install apisix by package name for better platform (x86_86 or aarch64) compatibility.
> chore: install apisix via package name instead of url

- .github/workflows/apisix-docker-dev-test.yaml
- compose/docker-compose.yaml
Because of a break change in APISIX, we have to use 9180 as the request port for the admin api.
The current dev image and other official version images use a same test task, which makes it impossible for us to adjust the admin api port in CI, because the official image is the release version and uses port 9180.
So, I split the CI of the dev image separately, it will run when the dev image is released.
> chore: sync APISIX use 9180 as default port of admin API

- .github/workflows/apisix_push_docker_hub.yaml
- Makefile
1、Build centos images for multiple platforms via CI.
2、Build latest images for multiple platforms via CI.
> feat: support publish multiarch centos

- debian/Dockerfile
Use a fixed version of the base image, so that we can use the [bashbrew](https://github.com/docker-library/bashbrew) tool to build the image, which is the requirement of the official docker image
> chore: remove debian IMAGE_BASE

- alpine/Dockerfile
Fixed CVE-* by alpine 3.15.6
trivy scan: Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
> feat: upgrade the version of apisix-base

- .github/workflows/apisix-docker-example-test.yaml
- .github/workflows/apisix_all_in_one_ci.yaml
- .github/workflows/apisix_push_docker_hub.yaml
- .gitmodules
- all-in-one/apisix/Dockerfile
- all-in-one/apisix/config.yaml
- alpine-dev/Dockerfile
- alpine/Dockerfile
- compose/apisix_conf/release/config.yaml
- compose/docker-compose-release.yaml
- example/apisix_conf/config.yaml
- example/docker-compose-arm64.yml
- example/docker-compose.yml
Fixes:
https://github.com/apache/apisix/issues/8002
https://github.com/apache/apisix-docker/issues/367
After APISIX released the 2.99.0 version of the image, some configurations were incompatible, causing the example to fail to start normally.
> fix: example unavailable

- example/docker-compose.yml
The etcd advertise client URL is used to inform the etcd client of the external URL of each node of its cluster, and our example sets it to `0.0.0.0:2379`, **which is clearly wrong**. We need to change it to the hostname of the etcd container `etcd`.
When this option is misconfigured, it will mislead the grpc load balancer included in the etcd client, which will try to connect to that non-existent server `0.0.0.0:2379`.
> fix: wrong etcd advertise url

- .github/workflows/dashboard_all_in_one_ci.yaml
- .github/workflows/dashboard_push_docker_hub.yaml
- Makefile
- all-in-one/apisix-dashboard/Dockerfile
- dashboard/Dockerfile.alpine
- dashboard/Dockerfile.centos
- example/docker-compose-arm64.yml
- example/docker-compose.yml
A CI is in a failed state because the image is not pushed due to a branch not being created, and you can ignore it.
> feat: bump APISIX Dashboard to 2.15.0

- Makefile
Re-add the wrongly deleted makefile code.
> fix: makefile build-dashboard phony missing

- centos/Dockerfile
- debian/Dockerfile
Signed-off-by: fengxsong <fengxsong@outlook.com>
fix https://github.com/apache/apisix-docker/issues/400#issuecomment-1373327999_
> fix: etcdctl missing due to PATH var is not set correctly

- docs/en/latest/example.md
- Removed profile flag from docker-compose up/dow command as the compose files do not contain any profile
specific configuration (anymore).
- Changed port for all admin API calls from 9080 to 9180 because the admin api is not exposed on 9080.
- Replaced ip addresses inside service upstream config with compose service names. CIDR for the bridge created by docker-compose might differ between machines, hostnames are fixed.
> chore: cleanup example documentation

- all-in-one/apisix/Dockerfile
refer to https://github.com/apache/apisix-docker/pull/419
This change misses other files and causes errors.
> fix: apisix all-in-one docker file

- example/docker-compose-arm64.yml
- example/docker-compose.yml
The latest tag should not be used.
> chore: specify the example apisix tag 3.1.0-debian

- all-in-one/apisix/Dockerfile
- debian/Dockerfile
To fix the problem with https://github.com/apache/apisix-ingress-controller/issues/1637 we decided to replace the `wget` in the apisix image with `curl` and made the change in
- https://github.com/apache/apisix-docker/pull/419
- https://github.com/apache/apisix-docker/pull/421
But we found that this caused problems for some users of build image base apisix: why did `wget` suddenly disappear?
Just like the changes in this PR https://github.com/apache/apisix-docker/pull/423
So we'd better keep both `wget` and `curl`.
> fix: keep both curl and wget in apisix image

- dashboard/Dockerfile.alpine
- dashboard/Dockerfile.centos
Use golang 1.19 in apisix-dashboard master branch.
https://github.com/apache/apisix-dashboard/blob/53cfc4cf35fbe5fe462b655f0e2b62f1f56195f8/api/go.mod#L3
> chore: update go version

- debian/Dockerfile
This PR updates `apisix` uid in the Debian Dockerfile to avoid conflicts.
The `uid` was initially introduced by https://github.com/apache/apisix-docker/issues/326
**Reason for the update**: to mount a file to the container built off this image for data persistency, users could encounter **Permission Denied** when container user is trying to write to the file on the host that's mounted. This could be resolved by changing the ownership of the mounted directory/file on host to `apisix` user with the same uid as in the container. The `apisix` user needs to be created on host.
For example:
```
sudo useradd -u 1001 apisix
mkdir ~/conf
touch ~/conf/config.yaml
sudo chown -R apisix:apisix ~/conf
```
However, it is quite common to have a pre-existing user with uid 1001. Hence this PR changes the …
> Update apisix uid in the Debian Dockerfile

- docs/en/latest/build.md
Document the way for building docker images from local source code.
> docs: add info about building docker image

- centos/docker-entrypoint.sh
- debian-dev/docker-entrypoint.sh
- debian/docker-entrypoint.sh
- redhat/docker-entrypoint.sh
fix: overwrite apisix.yaml
related to https://github.com/apache/apisix-docker/pull/494#issuecomment-1732756643
> fix: overwrite apisix.yaml

- .github/workflows/apisix_dev_push_docker_hub.yaml
The previous PR: #506, is missing one of the commits that I used to test it in my local fork. And the CI is failing: https://github.com/apache/apisix-docker/actions/runs/6323701339 because of the bug that exists due to the missing commit.
In the following line the environment variable has not been referenced correctly:
https://github.com/apache/apisix-docker/blob/c129ef542c7dabfae1f063bbe3dca7068ec37f64/.github/workflows/apisix_dev_push_docker_hub.yaml#L73
This has been fixed and I have added another commit that ensures the build fails when vulnerabilities exist.
> fix(ci): docker image scanning

- .github/workflows/apisix-docker-example-test-standalone.yaml
- centos/docker-entrypoint.sh
- debian-dev/docker-entrypoint.sh
- debian/docker-entrypoint.sh
- redhat/docker-entrypoint.sh
> fix: use sed replace yq

- debian/Dockerfile
- debian/docker-entrypoint.sh
This removes unnecessary burden from the image and reduces the chances of having CVEs.
> chore: remove unnecessary dependencies

- .github/workflows/apisix_dev_push_docker_hub.yaml
Following is the dependency graph for APISIX:
Most CVEs are from 3rd and 4th-level dependencies, which are difficult to upgrade/fix. Due to the existing CVEs the CI always fails and adding unfixable CVEs to an `allowlist` does not scale. Moreover, it is a problem in the long run for maintainers.
That's why I propose that we remove the docker image scanning workflow.
> chore: remove docker image scanning

- debian/Dockerfile
Fixes https://github.com/apache/apisix/issues/10593
During the container making process, the `ca-certificates` package was uninstalled, resulting in a non-existent /etc/ssl folder.
The current PR job is to keep the `ca-certificates` package.
> fix: save ca-certificates package

- compose/docker-compose-master.yaml
- compose/docker-compose-release.yaml
ETCD_ADVERTISE_CLIENT_URLS should not be 0.0.0.0.
Related issue: https://github.com/apache/apisix-docker/issues/454
The same issue was also reported by @bzp2010 to me for api7 docs.
> fix: update ETCD_ADVERTISE_CLIENT_URLS from 0.0.0.0 to FQDN

- debian-dev/docker-entrypoint.sh
- debian/docker-entrypoint.sh
- redhat/docker-entrypoint.sh
fix: config.yaml couldn't be volume mounted when using standalone Deployment modes (https://github.com/apache/apisix-docker/issues/529)
> fix: sed not suitable for docker if config.yaml is volume mounted #529

- .github/workflows/apisix_dev_docker_local_test.yaml
- Makefile
- debian-dev/Dockerfile.local
- debian-dev/docker-entrypoint.sh
Contains two fixes:
**1. Fix apisix-runtime dependency**
apisix is already dependent on the specified version of apisix-runtime.
**2. fix worker_events.sock address already.**
```shell
$ bin/apisix start
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua start
nginx: [emerg] bind() to unix:/home/bzp/code/apisix/conf/worker_events.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/home/bzp/code/apisix/conf/worker_events.sock failed (98: Address already in use)
```
ref: https://github.com/apache/apisix/pull/10732
The files `worker_events.sock` being exposed by container mounts and not being cleaned up on abnormal exits resulting in failure to start next time
> fix: apisix-debian-dev image failed to run

- .github/workflows/apisix-docker-example-test-standalone.yaml
- .github/workflows/apisix-docker-example-test.yaml
- .github/workflows/apisix_push_docker_hub.yaml
- Makefile
- debian/Dockerfile
- docs/en/latest/build.md
- example/docker-compose-arm64.yml
- example/docker-compose-standalone.yml
- example/docker-compose.yml
- redhat/Dockerfile
- redhat/docker-entrypoint.sh
Due to the missing deb/rpm arm architecture package, image with arm architecture is currently not supported.
> chore: release APISIX 3.8.0

- Makefile
- debian-dev/Dockerfile
- debian-dev/Dockerfile.local
- debian-dev/install-brotli.sh
- debian/Dockerfile
- debian/install-brotli.sh
- redhat/Dockerfile
- redhat/install-brotli.sh
This PR installs `brotli` on debain docker to use `brolti` plugin. 
- #530
Fixes #530 
Brolti is required to use the `brotli` plugin released in version 3.8.0 and above.
> chore: install brotli for debian and redhat

- Makefile
- all-in-one/apisix-dashboard/Dockerfile
It is known that publishing images depends on the rpm/deb package.
The apisix already supports publishing deb/rpm packages for ARM architecture.
https://github.com/api7/apisix-build-tools/actions/runs/7730314755
> ci: support uploading images of arm architecture

- .github/workflows/apisix-docker-example-test-standalone.yaml
- .github/workflows/apisix-docker-example-test.yaml
- .github/workflows/apisix_dev_docker_local_test.yaml
- .github/workflows/apisix_dev_push_docker_hub.yaml
- .github/workflows/apisix_push_docker_hub.yaml
- .github/workflows/dashboard_push_docker_hub.yaml
- all-in-one/apisix-dashboard/Dockerfile
- debian-dev/Dockerfile.local
This pull request includes updates to the CI workflow to address build issues.
1. **Build libyaml before installing lyaml**:
- Added a step to build and install libyaml before attempting to install the lyaml Lua module.
- This change resolves the issue where lyaml installation fails due to missing libyaml symbols.
2. **Switch from docker-compose to docker compose**:
- Updated the CI workflow to replace `docker-compose` with `docker compose` for compatibility with newer Docker versions.
> ci: include libyaml in image and use docker compose

- .github/workflows/apisix_push_docker_hub.yaml
The correct name of apisix container is here: https://github.com/apache/apisix-docker/actions/runs/10676375173/job/29589821558#step:3:1542.
The newer version of docker compose uses hyphens as delimiters instead of underscores.
> fix: container name in release workflow

- .github/workflows/apisix_dev_push_docker_hub.yaml
- .github/workflows/dashboard_push_docker_hub.yaml
Same as: https://github.com/apache/apisix-docker/pull/568.
> fix: use hyphens as delimiter instead of underscore

- .github/workflows/dashboard_push_docker_hub.yaml
Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of actions/upload-artifact or actions/download-artifact. Customers should update workflows to begin using v4 of the artifact actions as soon as possible.
> chore: upgrade actions/upload-artifact

- Makefile
- debian-dev/Dockerfile
- debian-dev/Dockerfile.local
- debian-dev/docker-entrypoint.sh
- debian/Dockerfile
- debian/docker-entrypoint.sh
- example/apisix_conf/config-standalone.yaml
- redhat/Dockerfile
- redhat/docker-entrypoint.sh
- utils/check_standalone_config.sh
- Removed modification of config.yaml in standalone mode.
- Added checks to make sure it uses data plane with yaml config provider.
- Added separate config file for standalone mode example.
> fix: avoid config.yaml modification in standalone mode due to read only file system.

- debian-dev/Dockerfile
After fix, can confirm the fix locally
> fix: failing build due to missing runtime dependency
