apache/apisix-docker

- alpine/Dockerfile
- example/docker-compose.yml
@moonming Please review it. thx.
> Upgrade to v0.6

- alpine/Dockerfile
@moonming Please review it. thx.
> Upgrade to v0.7

- alpine/Dockerfile
- example/apisix_conf/config.yaml
- example/docker-compose.yml
> Upgrade to v0.8

- alpine/Dockerfile
fixed https://github.com/iresty/docker-apisix/issues/17
> discard openresty image, and build from alpine directly.

- alpine/Dockerfile
> 改国内镜像源。适用中国国情

- README.md
- example/apisix_conf/config.yaml
```
docker run  --name test-api-gateway  -v ./example/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml  -v./example/apisix_log:/usr/local/apisix/logs  -p 8080:9080 -p  8083:9443 -d  iresty/apisix
```
> docker run add apisix_conf dir and update config.yaml

- README.md
- example/apisix_conf/config.yaml
- example/etcd_conf/etcd.conf.yml
add etcd config file and Run etcd server eg
> add etcd config file and Run etcd server eg

- example/apisix_conf/config.yaml
> Docker compose not working

- alpine/Dockerfile
- alpine/hooks/build
* updated 1.2 version for alpine.
* add alpine build hooks
* fix issue: the alpine image is too fat #43
> updated 1.2 version for alpine

- example/README.md
> Adding api key to header and introduction to lvh.me

- alpine/Dockerfile
- alpine/README.MD
- example/apisix_conf/config.yaml
modify alpine build version && add readme for alpine
> modify alpine build version && add readme for alpine

- example/docker-compose.yml
change etcd image in docker-compose
> fix: etcd image is not public

- example/README.md
- example/gen-config-yaml.sh
change config.sh to gen-config-yaml.sh
Fix #67
> [doc] change config.sh to gen-config-yaml.sh #67

- alpine/Dockerfile
fix https://github.com/apache/apisix-docker/pull/81
> feat: remove Dashboard

- example/apisix_conf/config.yaml
> change: make allow_admin 0.0.0.0/0 for test

- all-in-one/apisix-dashboard/Dockerfile
Fix: https://github.com/apache/apisix-dashboard/issues/1199
> fix: Change the structure of manager api cause build failure in build dashboard

- centos/Dockerfile
fix https://github.com/apache/apisix-docker/issues/116
> fix: update centos docker to 2.2.

- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
Fix: https://github.com/apache/apisix-docker/issues/119
> chore: modify the dockerfiles arg & add comments  for all-in-one Dockerfile

- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine/Dockerfile
Signed-off-by: fukiki <one.fhh@163.com>
Related to https://github.com/apache/apisix/issues/3469
> feat: add env variable of openssl for luarocks in dockerfile

- alpine/README.MD
> docs: improve the documentation of alpine

- .github/workflows/apisix-alpine-docker-test.yaml
- .github/workflows/apisix-centos-docker-test.yaml
- .gitignore
- Makefile
- alpine/docker-compose.yaml
- centos/Dockerfile
- centos/docker-compose.yaml
- example/apisix_conf/config.yaml
- example/docker-compose.yml
> CI: add apisix-docker test

- .github/workflows/apisix-docker-test.yaml
- Makefile
- README.md
- alpine/Dockerfile
- centos/Dockerfile
- example/docker-compose.yml
> feat: release 2.4

- example/dashboard_conf/conf.yaml
- example/docker-compose.yml
> feat: add apisix-dashbaord 

- docs/en/latest/config.json
https://github.com/apache/apisix-website/issues/298
> fix: for helm chart and docker ,tell users where they are 

- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
Add retry like https://github.com/apache/apisix/pull/4024
need to revert after luarocks back to normal
> fix: build failure caused by luarocks connection

- Makefile
- README.md
Fixed #147 
@Yiyiyimu have a look
> docs: Replace `docker build` command with `make`

- example/docker-compose.yml
* apache/apisix-dashboard:2.4
* apache/apisix:2.5-alpine
* bitnami/etcd:3.4.15
* nginx:1.19.0-alpine
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
> chore: upgrade example/docker-compose.yml versions

- README.md
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
Supplement for #156, to make all images do the error.log forward
> fix: add 'forward error to log' for local build

- example/docker-compose.yml
Closes #171 , #173 
Change etcd volumes data path in example module.
> fix: change etcd volumes data path in container

- .github/workflows/PULL_REQUEST_TEMPLATE
fixed: #182 (pull request template)
> feat: added PULL_REQUEST_TEMPLATE

- README.md
- example/docker-compose.yml
> chore: update dashboard version in example

- .github/workflows/apisix_push_docker_hub.yaml
- .github/workflows/dashboard_push_docker_hub.yaml
- example/apisix_conf/config.yaml
ref: https://issues.apache.org/jira/browse/INFRA-21756?focusedCommentId=17337769&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17337769
> ci: fix actions in docker push

- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine/Dockerfile
> fix: add pcre denpendency to all dockerfile

- Makefile
* better makefile output
* more flexible docker ENV inject support
https://github.com/NGX-AI/apisix-docker/blob/0576345238eabb7ef4e07dbffe100722ba365f1d/Makefile#L35-L38
> before
```bash
Makefile rules:
build-on-centos:      Build apache/apisix:xx-centos image
build-on-alpine:      Build apache/apisix:xx-alpine image
build-on-alpine-local:      Build apache/apisix:xx-alpine-local image
push-on-centos:       Push apache/apisix:xx-centos image
push-on-alpine:       Push apache/apisix:xx-alpine image
build-on-alpine-cn:          Build apache/apisix:xx-alpine image (for chinese)
build-all-in-one:            Build All in one Docker container for Apache APISIX
save-centos-tar:      tar apache/apisix:xx-centos image
save-alpine-tar:      tar apache/apisix:xx-alpine image
build-dashboard: …
```
> feat: more human friendly makefile output

- README.md
- docs/en/latest/example.md
Signed-off-by: leslie tsang <leslie.tsang@icloud.com>
> docs: optimize the reading experience

- .github/workflows/apisix-docker-test.yaml
- Makefile
- alpine/Dockerfile
- centos/Dockerfile
> feat: bump APISIX to 2.10.0

- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
replace `openresty` with`apisix-base`
> feat: replace openresty with apisix-base

- centos/Dockerfile
feat: install apisix with apisix rpm repo
> feat: install apisix with apisix rpm repo

- centos/Dockerfile
Build apisix image with apisix-base
> feat: build apisix image with apisix-base

- all-in-one/apisix/Dockerfile
> fix: all-in-one docker image build error

- .markdownlint.yml
- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix-dashboard/conf.yaml
- all-in-one/apisix/Dockerfile
- all-in-one/apisix/config.yaml
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
- alpine/hooks/build
- centos/Dockerfile
- centos/hooks/build
- compose/dashboard-compose.yaml
- compose/docker-compose.yaml
- example/apisix_conf/config.yaml
- example/docker-compose-alpine.yml
- example/docker-compose-arm64.yml
- example/docker-compose.yml
- example/etcd_conf/etcd.conf.yml
- example/prometheus_conf/prometheus.yml
Add ASF header for source code.
fix: #92 
Otherwise, I think we can add `license-checker` for this repository.
> docs: add ASF header

- .github/workflows/apisix-docker-test.yaml
- Makefile
- alpine-dev/Dockerfile
- alpine-local/Dockerfile
- alpine/Dockerfile
> fix(alpine): missing openldap

- example/docker-compose-arm64.yml
fix https://github.com/apache/apisix/issues/6086
> feat: add dashboard support for docker-compose-arm64.yml

- example/docker-compose-arm64.yml
from `2.11.0-alpine` to `2.12.1-alpine`
> feat: update apisix image version in `docker-compose-arm64.yml`

- example/docker-compose.yml
from 2.12.0-alpine to 2.12.1-alpine
> chore: update apisix image version in docker-compose.yml

- alpine/Dockerfile
> fix: pcre will based on apisix-base's version

- Makefile
- README.md
Resolved: #288 
Add dashboard-all-in-one tools and rewrite some section about build and launch dashboard.
> feat: add dashboard-all-in-one tools and update readme

- .github/workflows/apisix-docker-test.yaml
- Makefile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine/Dockerfile
- centos/Dockerfile
- example/docker-compose-arm64.yml
- example/docker-compose.yml
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
> feat: upgrade APISIX to 2.13.1

- .github/workflows/apisix-docker-test.yaml
- Makefile
- all-in-one/apisix/Dockerfile
- alpine-dev/Dockerfile
- alpine/Dockerfile
- centos/Dockerfile
- example/docker-compose-arm64.yml
- example/docker-compose.yml
> feat: upgrade APISIX to 2.14.0

- README.md
- example/docker-compose.yml
Since the previous README was written from the developer's point of view. Now you need to write from the user's perspective instead. So the README was refactored.
> docs: Refactor the README.

- README.md
>  docs: Modify the description

- debian-dev/Dockerfile
> feat: reduce dev image size

- .github/workflows/dashboard_push_docker_hub.yaml
> fix: yaml syntax in dashboard_push_docker_hub

- example/docker-compose-arm64.yml
alpine replaces debian
Fix #369
> ci: replace alpine to debian

- Makefile
> fix: avoid affecting latest image when pushing a LTS image

- example/docker-compose-arm64.yml
- example/docker-compose.yml
> feat: use latest so we don't need to hardcode the version

- .github/workflows/dashboard_push_docker_hub.yaml
Fix some condition error import in #358
> fix: dashboard image push condition

- all-in-one/apisix/Dockerfile
fix the issue https://github.com/apache/apisix-docker/issues/404
has test in my local
> chore: change the user for all-in-one

- debian/Dockerfile
Signed-off-by: fengshunli <1171313930@qq.com>
> fix: add curl module

- debian/Dockerfile
Signed-off-by: fengshunli <1171313930@qq.com>
> fix: replace wget with curl in apisix debian image(#419)

- all-in-one/apisix-dashboard/Dockerfile
> fix: add rust cargo support for `all-in-one` dashboard Dockerfile

- .github/workflows/apisix_dev_docker_local_test.yaml
- debian-dev/Dockerfile.local
Transferred from https://github.com/apache/apisix/pull/9586
> feat: support docker image creation from local codebase

- centos/docker-entrypoint.sh
- debian-dev/docker-entrypoint.sh
- debian/docker-entrypoint.sh
- redhat/docker-entrypoint.sh
fix https://github.com/apache/apisix-docker/issues/482
relevant  https://github.com/apache/apisix-docker/pull/487
> feat: do not overwrite existing yaml files

- docs/en/latest/build.md
Currently: https://apisix.apache.org/docs/docker/build/
> docs: update docs `Build an image from the source codes`

- .github/workflows/apisix_dev_push_docker_hub.yaml
Support docker image scanning for vulnerabilities.
Fixes: #504
> feat: support docker image scanning

- centos/docker-entrypoint.sh
- debian-dev/docker-entrypoint.sh
- debian/docker-entrypoint.sh
- redhat/docker-entrypoint.sh
> fix: docker desktop startup failure

- example/docker-compose-arm64.yml
update etcd environment variable
> update docker-compose-arm64 yaml

- .github/workflows/apisix_dev_docker_local_test.yaml
- .github/workflows/dashboard_all_in_one_ci.yaml
- .github/workflows/dashboard_push_docker_hub.yaml
- Makefile
- all-in-one/apisix-dashboard/Dockerfile
- all-in-one/apisix-dashboard/conf.yaml
- compose/dashboard-compose.yaml
- dashboard/Dockerfile.alpine
- dashboard/README.md
- debian-dev/Dockerfile
- debian-dev/Dockerfile.local
- debian-dev/docker-entrypoint.sh
This reverts commit 5720e8a520a34d7bf31a188576f4f3ea6ca07983. and delete the dashboard part in example directory
> feat: revert remove apisix-dashboard (#516)

- Makefile
- debian/docker-entrypoint.sh
fix: https://github.com/apache/apisix-docker/actions/runs/7525652871/job/20482350035#step:8:824
> fix: startup failure caused by file worker_events

- .github/workflows/apisix-docker-example-test-standalone.yaml
- .github/workflows/apisix-docker-example-test.yaml
- .github/workflows/apisix_push_docker_hub.yaml
- Makefile
- all-in-one/apisix-dashboard/Dockerfile
- debian/Dockerfile
- docs/en/latest/build.md
- example/docker-compose-arm64.yml
- example/docker-compose-standalone.yml
- example/docker-compose.yml
- redhat/Dockerfile
release new version of APISIX docker images
> chore: release APISIX 3.9.0

- .github/workflows/apisix-docker-example-test-standalone.yaml
- .github/workflows/apisix-docker-example-test.yaml
- .github/workflows/apisix_push_docker_hub.yaml
- Makefile
- debian/Dockerfile
- docs/en/latest/build.md
- example/docker-compose-arm64.yml
- example/docker-compose-standalone.yml
- example/docker-compose.yml
- redhat/Dockerfile
https://github.com/apache/apisix/blob/release/3.11/CHANGELOG.md#3110
> chore: release APISIX 3.11.0
